name: Run simulate on PNG Change

on:
  push:
    paths:
      - '**/*.png'
  pull_request:
    paths:
      - '**/*.png'

jobs:
  run-simulate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run simulate script
        run: npm run simulate
